version: '3'

services:

    #PHP Service
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: genesis-app
        restart: unless-stopped
        working_dir: /var/www
        tty: true
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - genesis-network

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: genesis-server
        restart: unless-stopped
        tty: true
        ports:
            - "8001:8001"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - db
        networks:
            - genesis-network

    #MySQL Service
    db:
        image: mysql:8.0
        container_name: genesis-db
        restart: unless-stopped
        tty: true
        ports:
            - "4306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            TZ: Europe/Kyiv
        volumes:
            - ./docker/mysql:/var/lib/mysql
        networks:
            - genesis-network

    #Redis Service
    redis:
        image: redis:7.2.3
        container_name: genesis-redis
        ports:
            - "6380:6379"
        volumes:
            - ./docker/redis:/data
        networks:
            - genesis-network
networks:
    genesis-network:
        driver: bridge
